site_name: CITORUS
site_url: http://docs.citorus.ru
site_description: CITORUS.DOCS
site_author: CITORUS team
site_favicon: favicon.png
copyright: CITORUS
pages:
pages:
- CITORUS.GIS: 'index.md'
extra_css: [extra.css]
