site_name: CITORUS.DOCS
site_url: http://docs.citorus.ru
site_description: CITORUS.DOCS
site_author: CITORUS team
site_favicon: favicon.ico
copyright: CITORUS
pages:
pages:
- CITORUS.GIS: 'index.md'
extra_css:
