site_name: QU-QU
site_url: http://docs.citorus.ru
site_description: GGGG
site_author: HHHH
site_favicon: favicon.png
copyright: CITORUS team
pages:
pages:
- CITORUS.GIS: 'index.md'
- About2: 'model.md'
extra_css: [extra.css]
