site_name: CITORUS.DOCS
site_url: http://docs.citorus.ru
site_description: CITORUS.DOCS
site_author: CITORUS team
site_favicon: favicon.ico
copyright: CITORUS
pages:
- 1. Общие сведения о Платформе автоматизации "ЦИТОРУС": 'index.md'
- 2. Документация подсистемы "Объектное хранилище": 'obj.md'
- 3. Документация по подсистемене WEB ГИС: 'model.md'
